// <auto-generated />
namespace SocialGames.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Refactoring_Player : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactoring_Player));
        
        string IMigrationMetadata.Id
        {
            get { return "202202181447000_Refactoring_Player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
