// <auto-generated />
namespace SocialGames.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PropGP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PropGP));
        
        string IMigrationMetadata.Id
        {
            get { return "202201032025534_Prop GP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
